/**
 * Regenerate all content for an existing post (condensed transcript, images, audio).
 *
 * Usage:
 *   npx tsx scripts/regenerate-post.ts <postId>
 */

import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import { initializeApp, cert, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

// ─── Firebase init ──────────────────────────────────────────────────────────
const serviceAccountJson = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
if (!serviceAccountJson) {
    console.error('❌ FIREBASE_SERVICE_ACCOUNT_KEY not found in .env.local');
    process.exit(1);
}

const serviceAccount = JSON.parse(serviceAccountJson);

if (!getApps().length) {
    initializeApp({
        credential: cert(serviceAccount),
        storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    });
}

const db = getFirestore();

// ─── Parse args ─────────────────────────────────────────────────────────────
const postId = process.argv[2];
if (!postId) {
    console.error('Usage: npx tsx scripts/regenerate-post.ts <postId>');
    process.exit(1);
}

// ─── Main ───────────────────────────────────────────────────────────────────
async function main() {
    // 1. Fetch the post
    const postDoc = await db.collection('posts').doc(postId).get();
    if (!postDoc.exists) {
        console.error(`❌ Post ${postId} not found`);
        process.exit(1);
    }

    const postData = postDoc.data()!;
    const uid = postData.authorId || postData.uid;
    const transcript = postData.content_raw;

    console.log(`\n📋 Post: ${postId}`);
    console.log(`📝 Title: ${postData.public_post?.title || postData.title || '(none)'}`);
    console.log(`👤 Author: ${uid}`);

    if (!transcript) {
        console.error('❌ Post has no stored transcript (content_raw) — cannot regenerate');
        process.exit(1);
    }

    console.log(`📄 Transcript length: ${transcript.length} chars`);

    // 2. Fetch user data
    const userDoc = await db.collection('users').doc(uid).get();
    const userData = userDoc.data();
    if (!userData) {
        console.error(`❌ User data not found for ${uid}`);
        process.exit(1);
    }

    const characterVoiceId = userData?.character_bible?.voice_id;
    const compiledBible = userData?.character_bible?.compiled_output?.ideal || [];
    const identity = userData?.identity;
    const gender = identity?.gender || '';

    const age = identity?.birthdate ? (() => {
        const bd = new Date(identity.birthdate);
        return Math.floor((Date.now() - bd.getTime()) / (365.25 * 24 * 60 * 60 * 1000));
    })() : null;
    const demographicHint = [
        identity?.gender,
        age ? `approximately ${age} years old` : null,
        identity?.ethnicity,
    ].filter(Boolean).join(', ');

    console.log(`🔄 Starting full regeneration...\n`);

    // 3. Import and run the shared pipeline
    const { processPostContent } = await import('../src/lib/ai/processPostContent');

    const pipelineResult = await processPostContent({
        transcript,
        uid,
        postId,
        compiledBible,
        demographicHint,
        characterVoiceId,
        gender,
        logPrefix: 'RegenerateScript',
    });

    if (!pipelineResult) {
        console.error('❌ Transcript was not deemed publishable');
        process.exit(1);
    }

    const { condensed, imagePrompts, audioFields } = pipelineResult;

    // 4. Update Firestore
    const updateData: Record<string, any> = {
        title: condensed.title,
        public_post: {
            condensed_transcript: condensed.messages,
        },
        condensed_editorial_note: condensed.editorial_note,
        image_style: 'per-message',
        image_prompts: imagePrompts,
        message_images: [],
        image_retries: 0,
        imagen_url: null,
        imagen_urls: [],
        visual_style: null,
        language: condensed.language,
    };

    if (audioFields.audio_url) {
        Object.assign(updateData, audioFields);
    }

    // Keep post hidden until images are generated
    updateData.is_public = false;

    await postDoc.ref.update(updateData);

    console.log(`\n✅ Post ${postId} regenerated!`);
    console.log(`   📝 Title: "${condensed.title}"`);
    console.log(`   💬 Messages: ${condensed.messages.length}`);
    console.log(`   🎨 Image prompts: ${imagePrompts.length}`);
    console.log(`   🔊 Audio: ${!!audioFields.audio_url}`);
    console.log(`   ⚠️  Post is_public=false — images need to be generated by Cloud Function`);

    // 5. Trigger image generation Cloud Function
    const cloudFunctionUrl = process.env.GENERATE_POST_IMAGES_URL;
    if (cloudFunctionUrl) {
        console.log(`\n🖼️  Triggering image generation...`);
        try {
            const res = await fetch(cloudFunctionUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ data: { postId } }),
            });
            console.log(`   Cloud Function response: ${res.status}`);
        } catch (err) {
            console.error('   ⚠️  Cloud Function trigger failed:', err);
        }
    } else {
        console.warn(`   ⚠️  GENERATE_POST_IMAGES_URL not set — images will not be generated automatically`);
    }

    console.log(`\n🎉 Done!`);
}

main().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
});
